(function(){
"use strict";
const FN="https://us-central1-neofind-f8213.cloudfunctions.net/neoEconomy",$=id=>document.getElementById(id);
const esc=s=>String(s==null?"":s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const op=()=>crypto.randomUUID?crypto.randomUUID():"op-"+Date.now()+"-"+Math.random();
const items=[["theme_sunset","Sunset Theme","Theme",250,"linear-gradient(135deg,#ff8a5b,#c850c0)"],["theme_forest","Forest Theme","Theme",350,"linear-gradient(135deg,#134e4a,#84cc16)"],["theme_violet","Violet Theme","Theme",400,"linear-gradient(135deg,#4c1d95,#c084fc)"],["profile_glow_cyan","Cyan Profile Glow","Profile",300,"linear-gradient(135deg,#00f2fe,#4facfe)"],["profile_glow_gold","Golden Profile Glow","Profile",650,"linear-gradient(135deg,#facc15,#f97316)"],["profile_sparkles","Profile Sparkles","Effect",500,"radial-gradient(circle,#fff 1px,#7c3aed 2px,#111827 70%)"]];
async function call(action,data={}){const u=auth&&auth.currentUser;if(!u)throw Error("LOGIN_REQUIRED");const token=await u.getIdToken(),r=await fetch(FN,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+token},body:JSON.stringify({data:{action,operationId:op(),...data}})});let b={};try{b=await r.json()}catch(e){}if(!r.ok||b.error||!b.result)throw Error(b.error&&b.error.message||"REQUEST_FAILED");return b.result}
function toast(s,bad){let n=$("neoEconomyToast");if(!n){n=document.createElement("div");n.id="neoEconomyToast";n.style.cssText="position:fixed;right:16px;bottom:76px;z-index:100102;background:#101820;color:#fff;border:1px solid #00f2fe;border-radius:12px;padding:12px 16px;font:14px system-ui";document.body.appendChild(n)}n.style.borderColor=bad?"#ff6262":"#00f2fe";n.textContent=s;clearTimeout(n.t);n.t=setTimeout(()=>n.remove(),3000)}
function mount(){if($("neoEconomyLauncher"))return;const s=document.createElement("style");s.textContent="#neoEconomyLauncher{position:fixed;right:18px;bottom:18px;z-index:100000;background:#102344;color:#fff;border:1px solid #00f2fe;border-radius:999px;padding:11px 16px;font:600 13px system-ui}#neoEconomyPanel{position:fixed;inset:0;z-index:100001;display:none;align-items:center;justify-content:center;padding:12px;background:#020711df;color:#e8f4ff;font:14px/1.5 system-ui}#neoEconomyPanel .card{width:min(850px,100%);max-height:92vh;overflow:auto;background:#0b1423;border:1px solid #29425d;border-radius:18px}#neoEconomyPanel header{position:sticky;top:0;background:#0b1423;display:flex;justify-content:space-between;padding:15px;border-bottom:1px solid #20334b}#neoEconomyPanel nav{display:flex;gap:6px;flex-wrap:wrap;padding:12px}#neoEconomyPanel button{cursor:pointer;border:1px solid #2d4561;background:#102238;color:#e8f4ff;border-radius:9px;padding:8px 11px}#neoEconomyPanel .active{border-color:#00f2fe;background:#063d50}#neoEconomyPanel main{padding:14px}#neoEconomyPanel .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px}#neoEconomyPanel article{background:#101d30;border:1px solid #263b54;border-radius:12px;padding:13px}#neoEconomyPanel .preview{height:50px;border-radius:9px;margin-bottom:9px}#neoEconomyPanel .muted{color:#9eb4ca;font-size:12px}#neoEconomyPanel input,#neoEconomyPanel select,#neoEconomyPanel textarea{box-sizing:border-box;width:100%;display:block;margin:6px 0 12px;padding:10px;background:#07111f;color:#fff;border:1px solid #2d4561;border-radius:8px;font:inherit}#neoEconomyPanel .row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid #1e3045}#neoEconomyPanel .empty{padding:24px;text-align:center;color:#9eb4ca;border:1px dashed #2d4561;border-radius:12px}.neo-ai-feedback{display:flex;gap:6px;margin:5px 0 12px}.neo-ai-feedback button{font-size:12px;padding:4px 9px}";
document.head.appendChild(s);const l=document.createElement("button");l.id="neoEconomyLauncher";l.textContent="✦ Neo Economy";l.onclick=()=>open("shop");document.body.appendChild(l);const p=document.createElement("div");p.id="neoEconomyPanel";p.innerHTML='<section class="card" role="dialog" aria-modal="true"><header><div><b>Neo Economy</b><div class="muted">Orbs · chests · cosmetics · safety</div></div><button id="neClose">Close</button></header><nav id="neTabs"></nav><main id="neBody"></main></section>';p.onclick=e=>{if(e.target===p)close()};document.body.appendChild(p);$("neClose").onclick=close;$("neTabs").onclick=e=>{const b=e.target.closest("[data-tab]");if(b)open(b.dataset.tab)};document.addEventListener("keydown",e=>{if(e.key==="Escape")close()})}
function close(){if($("neoEconomyPanel"))$("neoEconomyPanel").style.display="none"}
async function open(tab){mount();$("neoEconomyPanel").style.display="flex";$("neTabs").innerHTML=[["shop","Orb Shop"],["chests","Chest History"],["history","Orb History"],["report","Report"],["blocked","Blocked users"]].map(x=>'<button data-tab="'+x[0]+'" class="'+(tab===x[0]?"active":"")+'">'+x[1]+"</button>").join("");const b=$("neBody");b.innerHTML='<div class="empty">Loading…</div>';try{if(!auth.currentUser)throw Error("LOGIN_REQUIRED");if(tab==="shop")await shop(b);else if(tab==="chests"||tab==="history")await history(b,tab==="chests"?"chestHistory":"orbTransactions");else if(tab==="report")report(b);else await blocked(b)}catch(e){b.innerHTML='<div class="empty">'+(e.message==="LOGIN_REQUIRED"?"Sign in to use Neo Economy.":"Could not load this section.")+"</div>"}}
async function shop(b){const r=db.collection("users").doc(auth.currentUser.uid),v=await Promise.all([r.get(),r.collection("inventory").get()]),d=v[0].exists?v[0].data():{},owned=new Set(v[1].docs.map(x=>x.id));b.innerHTML="<p>Your balance: <b>"+Number(d.orbs||0)+" Orbs</b></p><div class=grid>"+items.map(x=>'<article><div class=preview style="background:'+x[4]+'"></div><b>'+x[1]+'</b><p class=muted>'+x[2]+'</p><p>'+x[3]+' Orbs</p><button data-buy="'+x[0]+'" '+(owned.has(x[0])?"disabled":"")+'>'+(owned.has(x[0])?"Owned":"Buy")+"</button></article>").join("")+"</div>";b.querySelectorAll("[data-buy]").forEach(x=>x.onclick=async()=>{x.disabled=true;try{const out=await call("buyCosmetic",{itemId:x.dataset.buy});toast("Purchased. Balance: "+out.orbs+" Orbs.");await open("shop")}catch(e){toast("Purchase failed. Check your balance.",true);x.disabled=false}})}
async function history(b,col){const s=await db.collection("users").doc(auth.currentUser.uid).collection(col).orderBy("createdAt","desc").limit(50).get();if(s.empty){b.innerHTML='<div class=empty>No history yet.</div>';return}b.innerHTML=s.docs.map(d=>{const x=d.data(),date=x.createdAt&&x.createdAt.toDate?x.createdAt.toDate().toLocaleString():"Timestamp pending";return col==="chestHistory"?'<div class=row><span><b>'+esc(x.chestLabel||x.chestType)+'</b><div class=muted>'+esc(date)+'</div></span><b>'+esc(x.rewardLabel||"Reward")+"</b></div>":'<div class=row><span><b>'+esc(x.reason||x.type)+'</b><div class=muted>'+esc(date)+'</div></span><b>'+(Number(x.delta)>0?"+":"")+Number(x.delta||0)+"</b></div>"}).join("")}
function report(b){b.innerHTML='<h3>Report a user or content</h3><label>Target user UID (optional)<input id=neReportUid maxlength=128></label><label>Content ID (optional)<input id=neReportTarget maxlength=160></label><label>Reason<select id=neReason><option value=spam>Spam</option><option value=impersonation>Impersonation</option><option value=harassment>Harassment</option><option value=inappropriate>Inappropriate content</option><option value=other>Other</option></select></label><label>Details<textarea id=neDetails maxlength=1200 rows=4></textarea></label><button id=neSendReport>Send report</button>';$("neSendReport").onclick=async()=>{try{await call("report",{targetUid:$("neReportUid").value.trim(),targetId:$("neReportTarget").value.trim(),reason:$("neReason").value,details:$("neDetails").value.trim()});toast("Report sent to moderation.");$("neDetails").value=""}catch(e){toast("Report failed.",true)}}}
async function blocked(b){const r=db.collection("users").doc(auth.currentUser.uid).collection("blockedUsers"),s=await r.get();b.innerHTML='<p class=muted>Block a user by Firebase UID.</p><label>User UID<input id=neBlockUid maxlength=128></label><button id=neBlock>Block user</button><h3>Your block list</h3>'+(s.empty?'<div class=empty>No blocked users.</div>':s.docs.map(d=>'<div class=row><code>'+esc(d.id)+'</code><button data-unblock="'+esc(d.id)+'">Unblock</button></div>').join(""));$("neBlock").onclick=async()=>{try{await call("blockUser",{targetUid:$("neBlockUid").value.trim(),blocked:true});toast("User blocked.");await open("blocked")}catch(e){toast("Could not block user.",true)}};b.querySelectorAll("[data-unblock]").forEach(x=>x.onclick=async()=>{try{await call("blockUser",{targetUid:x.dataset.unblock,blocked:false});await open("blocked")}catch(e){toast("Could not unblock user.",true)}})}
let blockedIds=new Set();
async function refreshBlocked(){if(!auth||!auth.currentUser)return;try{const snap=await db.collection("users").doc(auth.currentUser.uid).collection("blockedUsers").get();blockedIds=new Set(snap.docs.map(d=>d.id));applyBlocked()}catch(e){console.warn("Could not load blocked users",e)}}
function applyBlocked(){document.querySelectorAll("[data-author-uid]").forEach(el=>{const id=el.getAttribute("data-author-uid");el.style.display=id&&blockedIds.has(id)?"none":""})}
function feedback(){const root=$("neoAiMessages");if(!root||root.dataset.neFeedbackBound)return;root.dataset.neFeedbackBound="1";function add(row){if(!row.classList||!row.classList.contains("chat-row-them")||row.querySelector(".neo-ai-feedback"))return;const answer=row.querySelector(".chat-msg-them");if(!answer)return;const id=op(),bar=document.createElement("div");bar.className="neo-ai-feedback";[["up","Helpful"],["down","Not helpful"]].forEach(v=>{const x=document.createElement("button");x.textContent=v[1];x.onclick=async()=>{x.disabled=true;try{await call("feedback",{responseId:id,vote:v[0],model:window.neoAiSelectedModel||"unknown"});x.textContent="Saved"}catch(e){x.disabled=false;toast("Feedback could not be saved.",true)}};bar.appendChild(x)});answer.insertAdjacentElement("afterend",bar)}root.querySelectorAll(".chat-row-them").forEach(add);new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType!==1)return;add(n);n.querySelectorAll&&n.querySelectorAll(".chat-row-them").forEach(add)}))).observe(root,{childList:true,subtree:true})}
new MutationObserver(()=>applyBlocked()).observe(document.body,{childList:true,subtree:true});
window.NeoEconomy={call,open,close,secureBuyChest:t=>call("buyChest",{chestType:t}),secureOpenChest:t=>call("openChest",{chestType:t}),securePremium:()=>call("buyPremium"),secureMission:id=>call("claimMission",{missionId:id}),secureDailyChest:()=>call("claimDailyChest"),secureProgress:t=>call("recordMissionProgress",{missionType:t})};
document.addEventListener("DOMContentLoaded",()=>{mount();if(window.auth)auth.onAuthStateChanged(u=>{if(u){feedback();refreshBlocked()}})});if(document.readyState!=="loading")mount();
})();